package mx.gob.impi.rdu.util;

/******************************************************************************/
/* Name: IMPI
/* Date:
/* Description:
/******************************************************************************/
public abstract class Constantes {

    public static final Integer FIRST = 0;
    public static final Long FIRST_LONG = 0L;
    public static final Integer INIT = 1;
    public static final Short INIT_SHORT = 1;
    public static final Integer SECOND = 2;
    public static final Integer COLUMN_FOR_PANEL = 3;
    public static final Integer COLUMN_FOR_SMALL_PANEL = 2;
    public static final Integer ID_PROPIEDAD_PRECIOS = 6;
    public static final Integer ID_PROPIEDAD_MARCA = 2;
    public static final Integer NUM_IMAGE_GALERY = 10;
    public static final Long SISTEMA_PECUARIO = 2L;
    public static final Long SISTEMA_PRECIOS_AL_CONSUMIDOR = 4L;
    public static final Integer ID_PROPIEDAD_FUENTE = 33;
    public static final Integer ESTATUS_ENCUESTA = 1;
    public static final Short ESTATUS_ENCUESTA_SHORT = 1;
    public static final String NO_APLICA = "N/A";
    public static final String PREFIX_FOR_PANEL = "box";
    public static final String PREFIX_FOR_LIST = "list";
    public static final String PREFIX_FOR_BUTTON = "button";
    public static final String PREFIX_FOR_CHECKLIST = "checklist";
    public static final String PREFIX_FOR_IMG = "img";
    public static final String PREFIX_FOR_TEXT = "text";
    public static final String PREFIX_FOR_TEXTAREA = "textarea";
    public static final String PREFIX_FOR_CHECKBOX = "checkbox";
    public static final String PREFIX_FOR_PRODUCTO = "Producto";
    public static final String PREFIX_FOR_VARIEDAD = "Variedad";
    public static final String PREFIX_FOR_PROPIEDAD = "propiedad";
    public static final String PREFIX_FOR_PRODUCTO_VARIEDAD = "pv";
    public static final String PREFIX_FOR_COMMAND_LINK = "link";
    public static final String PREFIX_FOR_CALENDAR = "calendar";
    public static final String PREFIX_FOR_PRESENTACION_COMERCIAL = "Presentacion comercial";
    public static final String PREFIX_FOR_FUENTE = "Fuente";
    public static final String PREFIX_FOR_MARCA = "Marca";
    public static final String PREFIX_FOR_PRECIO_MIN = "Precio Minimo";
    public static final String PREFIX_FOR_PRECIO_MAX = "Precio Maximo";
    public static final String PREFIX_FOR_PRECIO_PROMEDIO = "Precio Promedio";
    public static final String PREFIX_FOR_PRECIO_FRECUENTE = "Precio Frecuente";
    public static final String PREFIX_FOR_ACTION = "Accion";
    public static final String PREFIX_FOR_DELETE = "Eliminar";
    public static final String CLASS_FOR_SMALL_PANEL = "ui-widget-bit-panel";
    public static final String CLASS_FOR_SCROLL_PANEL = "ui-scroll-custom-panel";
    public static final String CLASS_FOR_REQUIRED = "required";
    public static final String CLASS_FOR_HEADER = "dinamic-header-component";
    public static final String OPTION_DEFAULT = "Seleccione una opcion";
    public static final String SEPARATOR = "-";
    public static final Integer UI_COMPONENT_LISTA = 1;
    public static final Integer UI_COMPONENT_BUTTON = 5;
    public static final Integer UI_COMPONENT_CHECKLIST = 6;
    public static final Integer UI_COMPONENT_IMG = 4;
    public static final Integer UI_COMPONENT_TEXT = 2;
    public static final Integer UI_COMPONENT_TEXTAREA = 3;
    public static final Integer UI_COMPONENT_CHECKBOX = 7;
    public static final Integer UI_COMPONENT_COMMAND_LINK = 8;
    public static final Integer UI_COMPONENT_HTMLOUTTEXT = 9;
    public static final Integer UI_COMPONENT_CALENDAR = 10;
    public static final Integer ITEMS_PRECIOS = 4; //El no. de items para los precios min, max, promedio, frecuente
    public static final Integer SISTEMA = 1;
    public static final Integer SUBSISTEMA = 2;
    public static final Integer CLASE_DE_PRODUCTO = 3;
    public static final Integer CLASE = 3;
    public static final Integer PRODUCTO = 4;
    public static final Integer VARIEDAD = 5;
    public static final Integer PROPIEDAD_OBS = 7;
    public static final Integer VALOR_N = 6;
    public static final Integer VALOR_N_HORARIO_VERANO = 5;
    public static final Integer ID_ZONA_CENTRO = 1;
    public static final Integer ID_ZONA_PACIFICO = 2;
    public static final Integer ID_ZONA_NOROESTE = 3;
    public static final Long ID_PAIS_MEXICO = 918L;
//    Los perfiles de usuario
    public static final String ROLE_CAPTURISTA = "ROLE_CAPTURISTA";
    public static final String ROLE_ADMIN = "ROLE_ADMIN";
    public static final String ROLE_RESPONSABLE = "ROLE_RESPONSABLE";
    //subtipos de solicitudes
    public static final int AVISO = 3;
    public static final int MARCA = 1;
    public static final int NOMBRE = 2;
    public static final int REGMARCACOLECTIVA = 4;
    //tipos de marca
    public static final int NOMINATIVA = 1;
    public static final int DISENO = 2;
    public static final int MIXTA = 3;
    public static final int TRIDIMENSIONAL = 4;
    public static final int MIXTA_DENOMI_DIS_TRIDI = 5;
    public static final int MIXTA_DIS_FORMA_TRIDI = 6;
    public static final int MIXTA_DENOMI_DIS_FORMA_TRIDI = 7;
    //Estatus
    public static final Long INCOMPLETO = 1L;
    public static final String NOMBRE_PAIS = "MEXICO";
    public static final Long ID_PAIS = 918L;
    public static final Long ID_ENTIDAD_FEDERATIVA = 1L;
    public static final String NOMBRE_ENTIDAD_FEDERATIVA = "AGUASCALIENTES";
    public static final Long ID_ENTIDAD_DF = 9L;
    public static final String NOMBRE_ENTIDAD_DF = "DISTRITO FEDERAL";
    public static final String NOMBRE_NACIONALIDAD = "MEXICANA";
    public static final int EXISTE = 1;
    public static final int NO_EXISTE = 0;
    public static final long ACTIVO = 1L;
    public static final long INACTIVO = 0L;
    public static final int DESC_LIBRE = 1;
    public static final int RUBRO_GRAL = 2;
    public static final int PROD_SERV = 3;
    public static final int CRIT_CLASE = 0;
    public static final int CRIT_PRODUCTO = 1;
    public static final String PREFIX_FOLIO = "MA/E/";
    public static final String PREFIX_MARCA = "MA"; //ucm - extraer acuse
    public static final String SUBTIPO_FOLIO_CODIGO = "C";
    public static final String SUBTIPO_FOLIO_EXPEDIENTE = "E";
    public static final String SUBTIPO_FOLIO_MARCA = "D";
    public static final Long TRAMITE_ESTATUS_INCOMPLETA = 1L;
    public static final Long TRAMITE_ESTATUS_COMPLETA = 2L;
    public static final Long TRAMITE_ESTATUS_PAGADA = 3L;
    public static final Long TRAMITE_ESTATUS_VALIDADA = 4L;
    public static final Long TRAMITE_ESTATUS_RECIBIDA = 5L;
    public static final String MARCA_OPCION_SELECCION = "X";
    public static final String pattern_leyendasFiguras = "([A-Za-z]|[0-9]|\\s|\\|^|\u009F|\u00A1|\u00A2|\u00A3|\u00A4|\u00A5|\u00A6|\u00A7|\u00A8|\u00A9|\u00AA|\u00AB|\u00AC|\u00AC|\u00AE|\u00AF|\u00B0|\u00B1|\u00B2|\u00B3|\u00B4|\u00B5|\u00B6|\u00B7|\u2022|\u00B8|\u00B9|\u00BA|\u00BB|\u00BC|\u00BD|\u00BE|\u00BF|\u00C0|\u00C1|\u00C2|\u00C3|\u00C4|\u00C5|\u00C6|\u00C7|\u00C8|\u00C9|\u00CA|\u00CB|\u00CC|\u00CD|\u00CE|\u00CF|\u00D0|\u00D1|\u00D2|\u00D3|\u00D4|\u00D5|\u00D6|\u00D7|\u00D8|\u00D9|\u00DA|\u00DB|\u00DC|\u00DD|\u00DE|\u00DF|\u00E0|\u00E1|\u00E2|\u00E3|\u00E4|\u00E5|\u00E6|\u00E7|\u00E8|\u00E9|\u00EA|\u00EB|\u00EC|\u00ED|\u00EE|\u00EF|\u00F0|\u00F1|\u00F2|\u00F3|\u00F4|\u00F5|\u00F6|\u00F7|\u00F8|\u00F9|\u00FA|\u00FB|\u00FC|\u00FD|\u00FE|\u00FF|\\!|#|%|&|'|\\$|\\(|\\)|\\*|\\+|\\,|\\-|\\.|\\:|;|<|\\=|>|\\?|@|\\/|\\\\|\\[|\\]|_|\\^|`|\\{|\\|||}|~|\")+";
    public static final String pattern_productos_servicios = "([A-Za-z]|[0-9]|\u00D1|\u00F1|\\(|\\)|\\,|\\-|\\.|\\/|:|;|\\[|\\]|\\s|\u00DA|\u00DC)+";
    public static final String pattern_signoDistintivo = "([A-Za-z]|[0-9]|\u00D1|\u00F1|\u00E1|\u00C1|\u00E9|\u00C9|\u00ED|\u00CD|\u00F3|\u00D3|\u00FA|\u00DA|\u00FC|\u00DC|\\,|\\'|\\-|\\.|\\:|;|\\?|\u00BF|\u00A1|\\!|\\s|\\&|\u002F|\u00A8|\u00C4|\u00CB|\u00CF|\u00D6)+";
//    public static final String pattern_nombre_personas = "([A-Za-z]|[0-9]|\"|\u00D1|\u00F1|\u00E1|\u00C1|\u00E9|\u00C9|\u00ED|\u00CD|\u00F3|\u00D3|\u00FA|\u00DA|\u00DC|\\&|\\'|\\(|\\)|\\+|\\,|\\-|\\.|\\/|\\:|\\;|\\s)+";
//    public static final String pattern_nombre_personas = "([A-Z]|[a-z]|[0-9]|\\\u002A|\\\u002B|\\\u00F7|\\\u002D|\\\u002F|\"|\\#|\\$|\\%|\\&|'|\\\u002C|\\\u002E|\\\u003A|\\\u003B|\\\u003C|\\\u00BF|\\\u003F|\\\u00A1|\\\u0021|\\\u0040|\\\u0028|\\\u0029|\\\u005B|\\\u005D|\\\u005F|\\\u0060|\\\u007B|\\\u007C|\\\u00C2|\\\u00CA|\\\u00CE|\\\u00D4|\\\u00DB|\\\u00C1|\\\u00C9|\\\u00CD|\\\u00D3|\\\u00DA|\\\u00C4|\\\u00CB|\\\u00CF|\\\u00D6|\\\u00DC|\\\u00D1|\\\u00C0|\\\u00C3|\\\u00D5|\\\u00B0|\\\u00A2|\\\u00A7|\\\u00AE|\\\u00A8|\\\u00A5|\\\u00B5|\\\u00AC|\\\u00AB|\u00BB|\\s|\\\u00C7)+";
    
    
//    public static final String pattern_nombre_personas = "([A-Z]|[a-z]|[0-9]|\\\u002A|\\\u002B|\\\u00F7|\\\u002D|\\\u002F|\"|\\#|\\$|\\%|\\&|'|\\\u002C|\\\u002E|\\\u003A|\\\u003B|\\\u003C|\\\u00BF|\\\u003F|\\\u00A1|\\\u0021|\\\u0040|\\\u0028|\\\u0029|\\\u005B|\\\u005D|\\\u005F|\\\u007B|\\\u007C|\\\u00C2|\\\u00CA|\\\u00CE|\\\u00D4|\\\u00DB|\\\u00C1|\\\u00C9|\\\u00CD|\\\u00D3|\\\u00DA|\\\u00C4|\\\u00CB|\\\u00CF|\\\u00D6|\\\u00DC|\\\u00D1|\\\u00C0|\\\u00C3|\\\u00D5|\\\u00E1|\\\u00E9|\\\u00ED|\\\u00F3|\\\u00FA|\\\u00B0|\\\u00A2|\\\u00A7|\\\u00AE|\\\u00A8|\\\u00A5|\\\u00B5|\\\u00AC|\\\u00AB|\u00BB|\\s|\\\u00C7)+";
    
    public static final String pattern_nombre_personas = "([A-Z]|[a-z]|[0-9]|\\\u002A|\\\u002B|\\\u00F7|\\\u002D|\\\u002F|\"|\\#|\\$|\\%|\\&|'|\\\u002C|\\\u002E|\\\u003A|\\\u003B|\\\u003C|\\\u00BF|\\\u003F|\\\u00A1|\\\u0021|\\\u0040|\\\u0028|\\\u0029|\\\u005B|\\\u005D|\\\u005F|\\\u007B|\\\u007C|\\\u00C2|\\\u00CA|\\\u00CE|\\\u00D4|\\\u00DB|\\\u00C1|\\\u00C9|\\\u00CD|\\\u00D3|\\\u00DA|\\\u00C4|\\\u00CB|\\\u00CF|\\\u00D6|\\\u00DC|\\\u00D1|\\\u00C0|\\\u00C3|\\\u00D5|\\\u00E1|\\\u00E9|\\\u00ED|\\\u00F3|\\\u00FA|\\\u00B0|\\\u00A2|\\\u00A7|\\\u00AE|\\\u00A8|\\\u00A5|\\\u00B5|\\\u00AC|\\\u00AB|\\\u005E|\\\u0060|\\\u007E|\\\u00A0|\\\u00A1|\\\u00A2|\\\u00A3|\\\u00A4|\\\u00A5|\\\u00A6|\\\u00A7|\\\u00A8|\\\u00A9|\\\u00AA|\\\u00AB|\\\u00AC|\\\u00AD|\\\u00AE|\\\u00AF|\\\u00B0|\\\u00B1|\\\u00B2|\\\u00B3|\\\u00B4|\\\u00B5|\\\u00B6|\\\u00B7|\\\u00B8|\\\u00B9|\\\u00BA|\\\u00BB|\\\u00BC|\\\u00BD|\\\u00BE|\\\u00BF|\\\u00C0|\\\u00C1|\\\u00C2|\\\u00C3|\\\u00C4|\\\u00C5|\\\u00C6|\\\u00C7|\\\u00C8|\\\u00C9|\\\u00CA|\\\u00CB|\\\u00CC|\\\u00CD|\\\u00CE|\\\u00CF|\\\u00D0|\\\u00D1|\\\u00D2|\\\u00D3|\\\u00D4|\\\u00D5|\\\u00D6|\\\u00D7|\\\u00D8|\\\u00D9|\\\u00DA|\\\u00DB|\\\u00DC|\\\u00DD|\\\u00DE|\\\u00DF|\\\u00E0|\\\u00E1|\\\u00E2|\\\u00E3|\\\u00E4|\\\u00E5|\\\u00E6|\\\u00E7|\\\u00E8|\\\u00E9|\\\u00EA|\\\u00EB|\\\u00EC|\\\u00ED|\\\u00EE|\\\u00EF|\\\u00F0|\\\u00F1|\\\u00F2|\\\u00F3|\\\u00F4|\\\u00F5|\\\u00F6|\\\u00F7|\\\u00F8|\\\u00F9|\\\u00FA|\\\u00FB|\\\u00FC|\\\u00FD|\\\u00FE|\\\u00FF|\u00BB|\\s|\\\u00C7)+";
    
    
    public static final String pattern_direcciones = "([A-Za-z]|[0-9]|\\-|\\#|\\;|\\,|\\.|\\/|\\\\|\\_|'|\u00F7|\u00B0|\u00D1|\u00F1|\u00E1|\u00C1|\u00E9|\u00C9|\u00ED|\u00CD|\u00F3|\u00D3|\u00FA|\u00DA|\\s|\\\u0028|\\\u0029)+";
    public static final String PATTERN_CODIGO_POSTAL = "\\d{5}";
    public static final String PATTERN_EMAIL = "^([a-zA-Z0-9_\\-\\.]+)@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,3})$";
    public static final Long ANEXO_ACTA = 5L;
    public static final Long ANEXO_PRIORIDAD = 2L;
    public static final Long ANEXO_DOC_PODER = 1L;
    public static final Long ANEXO_DOC_PRIORIDAD = 2L;
    public static final Long ANEXO_DOC_LEGAL = 3L;
    public static final Long ANEXO_CONTRATO = 4L;
    public static final Long ANEXO_DOC_CONTVO = 5L;
    public static final Long ANEXO_REGLAS_USO = 6L;
    public static final Long ANEXO_OTROS = 7L;
    public static final Long ANEXO_DOC_RPG = 8L;
    public static final Long ANEXO_DISENO = 9L;
    public static final Long ANEXO_FE_ECHOS = 10L;
    public static final Long ANEXO_COMPROBANTE_PAGO = 17L;
    public static final Long ANEXO_TRADUCCION_DESCRIPCION = 45L;    
    public static final Long ANEXO_TRADUCCION_REIVINDICACION = 46L;
    public static final Long ANEXO_TRADUCCION_RESUMEN = 47L;
    public static final Long ANEXO_PRIORIDAD_PAT = 22L;
    public static final Long ANEXO_TRADUCCION_PRIORIDAD = 27L;
    public static final Long ANEXO_DIV_PREVIA_PAT = 21L;
    public static final Long ANEXO_NOTIFICACION_PAT = 24L;
    public static final Long ANEXO_ACREDITA_PERSONALIDAD = 19L;
    public static final Long ANEXO_CESION_DERECHOS = 20L;
    public static final Long ANEXO_CONST_MAT_BIOL = 29L;
    public static final Long ANEXO_DESCRIPCION_PATENTE = 15L;
    public static final Long ANEXO_REIVINDICACIONES_PATENTE = 16L;
    public static final Long ANEXO_HOJA_DESCUENT0 = 41L;
    public static final Long ANEXO_RESUMEN_MEMORIA = 43L;
    public static final Long ANEXO_DIVULGACION_PREVIA = 42L;
    public static final Long ANEXO_CARTA_PODER = 48L;
    public static final Long ANEXO_CONSTANCIA_RGP = 49L;
    public static final Long ANEXO_PODER_NOTARIAL = 50L;    
    public static final Long ANEXO_ACTA_CONSTITUTIVA = 51L;    
    public static final Long ANEXO_OTRO = 52L;
    public static final String PIPE = "|";
    public static final String OCSP = "OCSP";
    public static final String FIRMA_EMAIL_DE = "";
    public static final String FIG_CLASS_AVISO = "A";
    public static final String FIG_CLASS_MARCA = "M";
    public static final String FIG_CLASS_NOMBRE = "N";
    public static final String YEAR_FOLIO = "1985";
    public static final String REGISTRO_MARCA = "REGISTRO DE MARCA";
    public static final String REGISTRO_MARCA_COLECTIVA = "REGISTRO DE MARCA COLECTIVA";
    public static final String REGISTRO_AVISO_COMERCIAL = "REGISTRO DE AVISO COMERCIAL";
    public static final String PUBLICACION_NOMBRE_COMERCIAL = "PUBLICACION DE NOMBRE COMERCIAL";
    public static final Integer ESTATUS_CERT_AUTORIZADO = 1;
    public static final Integer ESTATUS_CERT_PENDIENTE = 2;
    public static final Integer ESTATUS_CERT_DESAHABILITADO = 3;
    public static final Long AREA_PATENTE = 4L;
    public static final Long AREA_MARCAS = 8L;
    public static final Long AREA_SIT = 20L;
    public static final Long AREA_PPI = 40L;
    public static final Long SOL_MODELO_PATENTE = 12L;
    //tipos de solictud
    public static final Long SOL_SIGNOS_DISTINTIVOS = 1L;  //marcas
    public static final Long SOL_RENOVACION = 2L;  //marcas
    public static final Long SOL_INS_TRANSMISION_DERECHOS = 3L;  //marcas
    public static final Long SOL_INS_LICENCIA_USO_FRANQUICIA = 4L;  //marcas
    public static final Long SOL_CAMBIO_DOMICILIO = 5L;  //marcas
    public static final Long SOL_TRANSFORMACION_CAMBIO_NOMBRE = 6L;  //marcas
    public static final Long SOL_AUT_USO_DENOMINACION_ORIGEN = 7L;  //marcas
    public static final Long SOL_SOLICITUD_PATENTE = 9L;  //patentes
    public static final Long SOL_MODELO_UTILIDAD = 10L;  //patentes
    public static final Long SOL_DISENO_INDUSTRIAL = 11L;  //patentes
    public static final Long SOL_CIRCUITO_INTEGRADO = 12L;  //patentes
    public static final Long SOL_BUSQUEDA_SIT = 20L;  //patentes
    public static final Long SOL_VIGILANCIA_SIT = 21L;  //patentes
    public static final Long SOL_CONVENIO_PERMITE_USO_DENOMINACION_ORIGEN = 13L;  //marcas
    //menu
    public static final int MNU_SOL_SIGNOS_DISTINTIVOS = 1;
    public static final int MNU_SOL_PREPARACION = 2;
    public static final int MNU_USUARIOS = 3;
    public static final int MNU_TABLERO_ELEC = 4;
    public static final int MNU_SALIR = 5;
    public static final int MNU_ADMIN_DIAS_INHABILES = 7;
    public static final int MNU_BITACORA_ERRORES = 8;
    public static final int MNU_SOL_PATENTES = 9;
    public static final int MNU_PROM_MAR_RENOVACION = 10;
    public static final int MNU_PROM_MAR_TRANSM_DERECHOS = 11;
    public static final int MNU_PROM_MAR_INS_LICENCIA_USO = 12;
    public static final int MNU_PROM_MAR_CAMBIO_DOMICILIO = 13;
    public static final int MNU_PROM_MAR_CAMBIO_NOMBRE = 14;
    public static final int MNU_PROM_MAR_AUT_USO_DENOMIN = 15;
    //Clase de personal
    public static final Long CLS_PERSONA_TITULAR = 2L;
    public static final Short CLS_PERSONA_SOLICITANE = 3;
    public static final Short CLS_PERSONA_DISTRIB_VENDEDOR = 4;
    public static final Long CLS_PERSONA_TIT_CEDENTE = 5L;
    public static final Long CLS_PERSONA_TITULAR_CESIONARIO = 6L;
    public static final Long CLS_PERSONA_lICENCIANTE_FRANQUICIANTE = 7L;
    public static final Long CLS_PERSONA_LICENCIATARIO_FRANQUICITARIO = 8L;
    public static final Long CLS_PERSONA_TITULAR_ANTERIOR = 9L;
    public static final Long CLS_PERSONA_TITULAR_ACTUAL = 10L;
    public static final Long CLS_PERSONA_APODERADO = 11L;
    public static final Long CLS_PERSONA_SOLICITANTE_PATENTES = 12L;
    public static final Long CLS_PERSONA_INVENTOR = 13L;
    public static final Long CLS_PERSONA_PARA_OIR_NOTIFICACIONES = 14L;
    public static final String pattern_numero_prioridad = "([A-Za-z]|[0-9]|\\s|\\,|\\-|\\.|\\/|\\[|\\]|_)+";
//    public static final String pattern_direccionesPatente = "([A-Za-z]|[0-9]|\\-|\\#|\\;|\\,|\\.|\\/|\\\\|\u00F7|\u00B0|\u00D1|\u00F1|\u00E1|\u00C1|\u00E9|\u00C9|\u00ED|\u00CD|\u00F3|\u00D3|\u00FA|\u00DA|\u00DC|\\s)+";
    public static final String pattern_direccionesPatente = "([A-Za-z]|[0-9]|\\\u00C4|\\\u00CB|\\\u00CF|\\\u00D6|\\\u00DC|\\\u00E4|\\\u00EB|\\\u00EF|\\\u00F6|\\\u00FC|\\-|\\#|\\;|\\,|\\.|\\/|\\\\|\u00F7|\u00B0|\u00D1|\u00F1|\u00E1|\u00C1|\u00E9|\u00C9|\u00ED|\u00CD|\u00F3|\u00D3|\u00FA|\u00DA|\\s)+";
    public static final String pattern_observacionesPatente = "([A-Za-z]|[0-9]|\u00D1|\u00F1|\u00E1|\u00C1|\u00E9|\u00C9|\u00ED|\u00CD|\u00F3|\u00D3|\u00FA|\u00DA|\u00FC|\u00DC|\\s|\\.|\\,|\\:|\\;|\\(|\\)|\\?|\\!|\u00D1|\u00F1|\")+";
    public static final String pattern_apoderado_rgp = "([0-9])+";
    public static final Long TIPO_SOL_PATENTE = 9L;
    public static final Long TIPO_SOL_MODELO_UTILIDAD = 10L;
    public static final Long TIPO_SOL_DISENO = 11L;
    public static final Long TIPO_SOL_ESQUEMA_TRAZADO = 12L;
    public static final Long TIPO_SOL_BUSQUEDA_SIT = 20L;
    public static final Long TIPO_SOL_VIGILANCIA_SIT = 21L;
    public static final Long SUBTIPO_PCT_PATENTE = 27L;
    public static final Long SUBTIPO_NORMAL_PATENTE = 9L;
    public static final Long SUBTIPO_PCT_MODELO_UTILIDAD = 11L;
    public static final Long SOL_EMPRESA_GRANDE = 1L;
    public static final Long SOL_EMPRESA_MED = 2L;
    public static final Long SOL_PERSONA_MORAL = 9L;
    
    public static final String oficinaDefaultPromociones= "MX";
    public static final int anioMinimoPromociones = 2010;
    public static final String nombreSolicitudPDF ="FORMATO SOLICITUD";
    
     public static final int[] bytesGifAnimado = new int[]{0x4E,0x45,0x54,0x53,0x43,0x41,0x50,0x45};   
     public static final String URL_INDEX_PATENTES ="/rdu-ppi";
     public static final int idFechaPrevia =0;
     public static final int idFechaPresent =1;
     public static final int idFechaPriorid =2;
     public static final int rango12Meses =12;
     public static final int rango6Meses =6;
     public static final String TIPO_SOLICITUD_DI = "Diseño Industrial";
     public static final String TIPO_SOLICITUD_MU = "Modelo de Utilidad";
     public static final String TIPO_SOLICITUD_BU = "Búsqueda";
     public static final String TIPO_SOLICITUD_VI = "Vigilancia";
     public static final String SIN_NUMERO = "S/N";
     public static final String FORMATO_FECHA = "dd/MM/yyyy"; 
}
